// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHgf9m1_hfz_XThB86b4PJNSnkT15x3C8',
    appId: '1:647435077942:web:82e7258bf2e64239864b97',
    messagingSenderId: '647435077942',
    projectId: 'hadith-diary',
    authDomain: 'hadith-diary.firebaseapp.com',
    storageBucket: 'hadith-diary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACCrUbMeAivMmGBcv_0m5g_TNQVjgfg8Q',
    appId: '1:647435077942:android:74bbcf373ae3ba3e864b97',
    messagingSenderId: '647435077942',
    projectId: 'hadith-diary',
    storageBucket: 'hadith-diary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeO8E_mYfwqvoWzmD2bapHdcffZig5qpA',
    appId: '1:647435077942:ios:fb4cc1f309a4b969864b97',
    messagingSenderId: '647435077942',
    projectId: 'hadith-diary',
    storageBucket: 'hadith-diary.appspot.com',
    iosBundleId: 'com.example.hadithDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeO8E_mYfwqvoWzmD2bapHdcffZig5qpA',
    appId: '1:647435077942:ios:96ffed9f534d12d8864b97',
    messagingSenderId: '647435077942',
    projectId: 'hadith-diary',
    storageBucket: 'hadith-diary.appspot.com',
    iosBundleId: 'com.example.hadithDiary.RunnerTests',
  );
}
